version: '3.8'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - 3366:3366
    environment:
      MYSQL_USER: gvendas
      MYSQL_PASSWORD: gvendas
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gvendas_db